version: '3'
services:
  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20210609
    container_name: svfe-api-firmador
    ports:
      - "8113:8013"
    env_file:
      - ./svfe-api.env
    volumes:
      - "./temp:/uploads"
